# SPDX-FileCopyrightText: 2025 Cooper Dalrymple (@relic-se)
#
# SPDX-License-Identifier: MIT

name: GitHub Release Actions

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    if: github.repository_owner == 'relic-se'
    runs-on: ubuntu-latest
    steps:
    - name: Set up requested Python version
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Versions
      shell: bash
      run: |
        python3 --version
    - name: Checkout Current Repo
      uses: actions/checkout@v4
      with:
        submodules: true
        show-progress: false
    - name: Install reqs
      shell: bash
      run: |
        pip install -r build/requirements.txt
    - name: Build assets
      shell: bash
      run: |
        python build/build.py
    - name: Upload Release Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        asset_path: "dist/*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        upload_url: ${{ github.event.release.upload_url }}
